"""initial migration

Revision ID: 0d0cb0999d94
Revises: 280b3a78e0dd
Create Date: 2021-10-13 23:01:30.859788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0cb0999d94'
down_revision = '280b3a78e0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_save_code_timestamp', table_name='save_code')
    op.drop_table('save_code')
    op.drop_index('ix_temp_code_timestamp', table_name='temp_code')
    op.drop_table('temp_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('temp_code', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('code_name', sa.VARCHAR(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_code_timestamp', 'temp_code', ['timestamp'], unique=False)
    op.create_table('save_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_code', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('code_name', sa.VARCHAR(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_save_code_timestamp', 'save_code', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
