"""Initial migration.

Revision ID: 280b3a78e0dd
Revises: 38ff864d8679
Create Date: 2021-08-05 19:51:26.202810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280b3a78e0dd'
down_revision = '38ff864d8679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_code', sa.Column('code_name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_code', 'code_name')
    # ### end Alembic commands ###
