"""SaveCode table

Revision ID: 38ff864d8679
Revises: ec4dd16bef97
Create Date: 2018-03-07 01:06:39.601922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ff864d8679'
down_revision = 'ec4dd16bef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=10000), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_save_code_timestamp'), 'save_code', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_save_code_timestamp'), table_name='save_code')
    op.drop_table('save_code')
    # ### end Alembic commands ###
